export const OneHundred = 100;
export const AxisRange = [0, 100];
export const LeftMin = 20;
export const LeftMax = 80;
export const HoverPositionLowerThreshold = 150;
export const HoverPositionUpperThreshold = 315;
export const HoverPositionLowerThresholdMobile = 70;
export const HoverPositionUpperThresholdMobile = 180;
export const rateSlopeLow = 0;
export const DAYS_IN_YEAR = 365;
export const PND_RATE_VALUE = 1; //PNDの価格(今は固定、後にオラクルから取得するようにする)
export const REWARD_BONUS_RATE_VALUE = 1; //PNDが1ドルを下回った時に発生するボーナス倍率
export const LightGrayColorCode = "#949494";
export const LightBlackColorCode = "#3a4450";
export const PinkColorCode = "#FF2E6C";
export const MossGreenColorCode = "#3B8593";
